apiVersion: v1
kind: Service
metadata:
  name: flask-calculator-service
spec:
  type: NodePort
  selector:
    app: flask-calculator
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007   # NodePort range: 30000â€“32767
