apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-calculator-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-calculator
  template:
    metadata:
      labels:
        app: flask-calculator
    spec:
      containers:
      - name: flask-calculator
        image: enigma0713/flask_calculator:v1
        ports:
        - containerPort: 8080
